### PR TITLE
Null pointer solved and text field removed

### PR DESCRIPTION
**Pull request by danielemaddaluno**
Null pointer solved in case there is no is_echo, removed text field it's already in the parent class

### CODE REVIEW

**Comment by alvin-reyes** [comment]
@danielemaddaluno, can you create a pull request directly to our master? This is so TRAVIS CI can initiate the build with your changes on it.

**Comment by danielemaddaluno** [comment]
Ok, no problem, I'll do it as soon as possible 👍 ☺

**Comment by alvin-reyes** [comment]
Thank you! Once you've done that, please close this one and I'll let you know if there are any feedback on the other one.

**Comment by danielemaddaluno** [comment]
Pull replied in the master

**Pull request closed without merging**
